default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: myuser
  password: mypassword

development:
  <<: *default
  database: blogapp_development 

test:
  <<: *default
  database: blogapp_test


production:
  <<: *default
  database: blogapp_production
  username: myuser    
  password: mypassword
  host: your_postgres_host
